# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: tang02320
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080