version: '3'
services:
  # See https://docs.docker.com/engine/swarm/stack-deploy/
  # for a complete swarm deploy demo
  # C:\Users\giorgig\starter-kit\ahab>docker run -p 9000:9000 --rm -v   
  sonar:
    container_name: sonar7
    image: sonarqube:7.9.1-community
    restart: always
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.90"
          memory: 2048M
    volumes:
      - "$S/conf:/opt/sonarqube/conf"      
      - "$S/extensions:/opt/sonarqube/extensions"
      - "$S/data:/opt/sonarqube/data"



