version: '3.1'
# docker stack deploy -c stack.yml wordpress
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 2080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - $wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - $db:/var/lib/mysql
  # Refer https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
  elasticsearch:
    # Consider 6.4 for elasticpress
    image: elasticsearch:7.5.0
    #image: elasticsearch:6.4.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $elasticdata:/usr/share/elasticsearch/data
